# Generated by Django 3.1.7 on 2021-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('family_name', models.CharField(max_length=30)),
                ('phone_number', models.BigIntegerField()),
                ('medical_association_id', models.IntegerField(unique=True)),
                ('clinic_address', models.TextField()),
                ('medical_expertise', models.TextField()),
                ('off_days', models.TextField(null=True)),
                ('opening_time', models.TextField(default='8:00AM', null=True)),
                ('closing_time', models.TextField(default='12:00PM', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_username', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
